In [13]:
# import pandas as pd

# df = pd.read_excel("experiment_stimuli.xlsx")

# contrastive_df = df.loc[df["condition"] == "contrastive"].copy()

# region_cols = [f"r{i}" for i in range(1, 8)]
# contrastive_df["sentence"] = (
#     contrastive_df[region_cols]
#     .fillna("")
#     .astype(str)
#     .agg(" ".join, axis=1)
#     .str.replace(r"\s+", " ", regex=True)
#     .str.strip()
# )

# # Item should be integer, not float
# contrastive_df["item"] = contrastive_df["item"].astype(int)

# new_df = contrastive_df[["item", "sentence"]].copy()
# new_df

# # Export this new df rows to a txt separated by new lines, with the sentences following the item no.
# with open("contrastive_sentences.txt", "w") as f:
#     for index, row in new_df.iterrows():
#         f.write(f"{row['item']}: {row['sentence']}\n")

In [14]:
import pandas as pd

df = pd.read_excel("contrastive_results.xlsx")
print(df.columns.tolist())

['Timestamp', 'Prolific ID:', 'Anyanyelve:', '18 éves koráig tanulmányait Magyarországon végezte?', 'Neme:', 'Kora:', 'Tegnap reggel Anna többek között egy banánt evett.', 'Tegnap reggel a kisfiú többek között egy ceruzát kapott.', 'Tegnap a műhelyben az asztalos többek között egy könyvespolcot készített.', 'Tavaly ilyenkor a katonaság többek között a helikoptert tesztelte.', 'Tegnap este én többek között a fánkot sütöttem.', 'Hallottam hogy Éva többek között a tulipánt szereti.', 'Tegnap este mi többek között ásványvizet vettünk.', 'Ma reggel Eszter többek között kávét ivott.', 'Régen az iskolában a diákok többek között németet tanultak.', 'Tavaly nyáron Marci többek között egy lepkét fedezett fel.', 'Múlt hétvégén a turisták többek között egy robogót béreltek ki.', 'Tíz évvel ez előtt a kertben a férfi többek között egy fenyőfát ültetett el.', 'Múltkor az állatkertben a gyerekek többek között az elefántot nézték meg.', 'Múltkor a könyhában a szerelő többek között a hűtőt üzemelte be.', 'Éjjel a szigeten a kalóz többek között az aranyat találta meg.', 'Ma ebédre a nagyi többek között levest tálalt fel.', 'Általában a műhelyben ez a szabó többek között ingeket foltozott be.', 'Tegnap este a bálon Péter többek között Marit kérte fel.', 'Tegnap reggel Anna többek között nem egy nem kettő alma eszik és más.', 'Ki adja majd többek között a könyveket gyerek nekik felnőtt nekik és oda?', 'Tegnap a reptéren az asztalos többek között csak egy hajtóművet épített.', 'Tavaly olyankor a hadsereg többek között az összes téglát megette.', 'Tegnap este én többek között sok tankot sütöttem.', 'Hallottam hogy Magdi sok árvaházat ültetett a kertben.', 'Tegnap este mi többek között jegesmedvéket repültünk.', 'Ma reggel Tilda többek között a kedvenc pincérét itta meg.', 'Régen az iskolában a diákok többek között holdat fogtak.', 'Tavaly nyáron Béla többek között orvosokat főzték a levesbe.', 'Múlt hétvégén az alpinisták többek között egy kutyaszánt bérelünk ki.', 'Tíz évvel ez előtt a kertben a flamingó többek között egy ügyvédet ásták el.', 'Múltkor az cirkuszban a gyerekek többek között az narancsot néztétek meg.', 'Múltkor a könyhában a szerelő többek között a leghíresebb koktélt rendeltem meg.', 'Éjjel a szigeten a kalózod többek között a kincseket kerested meg.', 'Ma ebédre a nagyi többek között mobiltelefont tálaltak fel.', 'Általában a szabók többek között citrommal ittuk ingeket.', 'Tegnap este a gálán Miklós többek között Nórát döntöttem el.', 'Most itt válassza ki a négyest, ez csak egy ellenörző kérdés.', 'Ki adja majd a könyveket gyerek nekik felnőtt nekik és oda ki?', 'Most ez mondat nincs jó, válaszolni kell egyes karika, jó?']

In [15]:
# Rename 'Anyanyelve:' to 'native_language' and '18 éves koráig tanulmányait Magyarországon végezte?' to 'schooling', 'Neme:' to 'gender', and 'Kora:' to 'age'. 
df.rename(
    columns={
        'Anyanyelve:': 'native_language',
        '18 éves koráig tanulmányait Magyarországon végezte?': 'schooling',
        'Neme:': 'gender',
        'Kora:': 'age'
    }, inplace=True
)

print(df.columns.tolist())

['Timestamp', 'Prolific ID:', 'native_language', 'schooling', 'gender', 'age', 'Tegnap reggel Anna többek között egy banánt evett.', 'Tegnap reggel a kisfiú többek között egy ceruzát kapott.', 'Tegnap a műhelyben az asztalos többek között egy könyvespolcot készített.', 'Tavaly ilyenkor a katonaság többek között a helikoptert tesztelte.', 'Tegnap este én többek között a fánkot sütöttem.', 'Hallottam hogy Éva többek között a tulipánt szereti.', 'Tegnap este mi többek között ásványvizet vettünk.', 'Ma reggel Eszter többek között kávét ivott.', 'Régen az iskolában a diákok többek között németet tanultak.', 'Tavaly nyáron Marci többek között egy lepkét fedezett fel.', 'Múlt hétvégén a turisták többek között egy robogót béreltek ki.', 'Tíz évvel ez előtt a kertben a férfi többek között egy fenyőfát ültetett el.', 'Múltkor az állatkertben a gyerekek többek között az elefántot nézték meg.', 'Múltkor a könyhában a szerelő többek között a hűtőt üzemelte be.', 'Éjjel a szigeten a kalóz többek között az aranyat találta meg.', 'Ma ebédre a nagyi többek között levest tálalt fel.', 'Általában a műhelyben ez a szabó többek között ingeket foltozott be.', 'Tegnap este a bálon Péter többek között Marit kérte fel.', 'Tegnap reggel Anna többek között nem egy nem kettő alma eszik és más.', 'Ki adja majd többek között a könyveket gyerek nekik felnőtt nekik és oda?', 'Tegnap a reptéren az asztalos többek között csak egy hajtóművet épített.', 'Tavaly olyankor a hadsereg többek között az összes téglát megette.', 'Tegnap este én többek között sok tankot sütöttem.', 'Hallottam hogy Magdi sok árvaházat ültetett a kertben.', 'Tegnap este mi többek között jegesmedvéket repültünk.', 'Ma reggel Tilda többek között a kedvenc pincérét itta meg.', 'Régen az iskolában a diákok többek között holdat fogtak.', 'Tavaly nyáron Béla többek között orvosokat főzték a levesbe.', 'Múlt hétvégén az alpinisták többek között egy kutyaszánt bérelünk ki.', 'Tíz évvel ez előtt a kertben a flamingó többek között egy ügyvédet ásták el.', 'Múltkor az cirkuszban a gyerekek többek között az narancsot néztétek meg.', 'Múltkor a könyhában a szerelő többek között a leghíresebb koktélt rendeltem meg.', 'Éjjel a szigeten a kalózod többek között a kincseket kerested meg.', 'Ma ebédre a nagyi többek között mobiltelefont tálaltak fel.', 'Általában a szabók többek között citrommal ittuk ingeket.', 'Tegnap este a gálán Miklós többek között Nórát döntöttem el.', 'Most itt válassza ki a négyest, ez csak egy ellenörző kérdés.', 'Ki adja majd a könyveket gyerek nekik felnőtt nekik és oda ki?', 'Most ez mondat nincs jó, válaszolni kell egyes karika, jó?']

In [16]:

# Show the results for these 4 columns one by one is a simple and meaningful way.
print("Native Language:")
print(df['native_language'].value_counts())
print()

print("Schooling:")
print(df['schooling'].value_counts())
print()

print("Gender:")
print(df['gender'].value_counts())
print()

print("Age:")
print(df['age'].value_counts())
print()

Native Language:
native_language
Magyar    15
Name: count, dtype: int64

Schooling:
schooling
Igen    15
Name: count, dtype: int64

Gender:
gender
Férfi    8
Nő       7
Name: count, dtype: int64

Age:
age
50    3
24    2
33    2
55    1
29    1
31    1
49    1
41    1
28    1
37    1
25    1
Name: count, dtype: int64

In [17]:
# Calculate mean, and sd for age
print(f"Mean age: {df['age'].mean()}")
print(f"Standard deviation of age: {df['age'].std()}")

Mean age: 37.266666666666666
Standard deviation of age: 10.970523276142346

In [18]:
df

# Transpose this table
df = df.T

# Drop Timestamp, native_language, schooling, gender, and age columns
df.drop(['Timestamp', 'native_language', 'schooling', 'gender', 'age'], axis=0, inplace=True)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
Prolific ID:,5df2235d5a34251266ea645e,60245c7c3df42d131232cedb,695243059cda2a858a8374c8,5c48be0496d59b000183e68d,6a23d1de59ebe30c551cc503,6a4407786c0afee02f74e0d0,6150053fddd36a6892b8f13c,6932bf332627def0f1f8a46b,6a2d5bc0bd0691ccc75b8ce2,5a913d2cf0536100017196d8,5c69824b98f65b0001353794,61242dd5be1a06b174975a1f,693e69d41e0de9c8fad42703,5c66cc9246bfc200019044b8,608c08b442036ab091bbba75
Tegnap reggel Anna többek között egy banánt evett.,6,7,7,7,6,7,7,7,4,6,5,7,7,7,5
Tegnap reggel a kisfiú többek között egy ceruzát kapott.,6,7,7,7,5,7,7,7,6,7,5,7,7,6,7
Tegnap a műhelyben az asztalos többek között egy könyvespolcot készített.,6,7,7,7,7,7,7,7,6,6,5,7,7,7,7
Tavaly ilyenkor a katonaság többek között a helikoptert tesztelte.,6,7,7,7,6,6,7,7,5,4,5,7,7,3,4
Tegnap este én többek között a fánkot sütöttem.,6,6,7,6,6,2,7,7,1,6,6,5,6,4,7
Hallottam hogy Éva többek között a tulipánt szereti.,5,7,7,7,6,4,7,7,4,5,5,7,7,7,6
Tegnap este mi többek között ásványvizet vettünk.,6,7,7,5,4,5,7,6,3,5,5,6,7,2,7
Ma reggel Eszter többek között kávét ivott.,6,7,7,7,6,7,7,5,2,7,6,5,5,6,7
Régen az iskolában a diákok többek között németet tanultak.,3,7,7,7,7,7,7,6,4,5,5,6,7,3,7
Tavaly nyáron Marci többek között egy lepkét fedezett fel.,5,7,7,7,4,6,7,7,3,6,6,6,6,7,2
Múlt hétvégén a turisták többek között egy robogót béreltek ki.,4,7,7,6,4,3,7,7,5,6,6,5,3,6,7
Tíz évvel ez előtt a kertben a férfi többek között egy fenyőfát ültetett el.,1,7,6,6,6,6,7,7,3,5,5,4,7,4,7
Múltkor az állatkertben a gyerekek többek között az elefántot nézték meg.,5,7,7,7,6,7,7,7,3,7,5,7,7,6,6
Múltkor a könyhában a szerelő többek között a hűtőt üzemelte be.,6,6,2,7,3,1,6,7,1,7,1,1,4,6,4
Éjjel a szigeten a kalóz többek között az aranyat találta meg.,2,6,7,7,3,5,7,7,3,5,5,7,6,6,3
Ma ebédre a nagyi többek között levest tálalt fel.,1,7,7,7,6,7,7,7,3,7,6,6,7,2,7
Általában a műhelyben ez a szabó többek között ingeket foltozott be.,3,4,2,6,6,1,5,1,3,3,1,2,4,3,4
Tegnap este a bálon Péter többek között Marit kérte fel.,6,7,6,6,6,3,7,7,6,5,6,7,7,6,7
Tegnap reggel Anna többek között nem egy nem kettő alma eszik és más.,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1
Ki adja majd többek között a könyveket gyerek nekik felnőtt nekik és oda?,1,2,1,1,1,1,1,1,1,1,1,1,1,2,1
Tegnap a reptéren az asztalos többek között csak egy hajtóművet épített.,4,1,2,4,1,4,1,1,1,6,6,3,3,5,1
Tavaly olyankor a hadsereg többek között az összes téglát megette.,1,1,2,1,1,1,1,6,1,5,1,1,2,4,1
Tegnap este én többek között sok tankot sütöttem.,1,1,2,1,1,1,1,2,2,1,1,1,2,4,1
Hallottam hogy Magdi sok árvaházat ültetett a kertben.,1,1,2,1,1,1,1,1,2,2,3,1,1,3,1
Tegnap este mi többek között jegesmedvéket repültünk.,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1
Ma reggel Tilda többek között a kedvenc pincérét itta meg.,1,1,2,1,1,1,1,1,1,2,2,1,3,2,1
Régen az iskolában a diákok többek között holdat fogtak.,1,1,1,1,1,1,1,1,2,1,2,1,2,2,1
Tavaly nyáron Béla többek között orvosokat főzték a levesbe.,1,1,1,1,1,1,1,1,1,1,3,1,1,3,1
Múlt hétvégén az alpinisták többek között egy kutyaszánt bérelünk ki.,1,1,1,1,1,1,1,1,1,2,2,1,1,7,1
Tíz évvel ez előtt a kertben a flamingó többek között egy ügyvédet ásták el.,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1
Múltkor az cirkuszban a gyerekek többek között az narancsot néztétek meg.,1,1,1,2,1,2,1,1,1,3,2,1,2,1,3
Múltkor a könyhában a szerelő többek között a leghíresebb koktélt rendeltem meg.,1,1,1,1,4,1,1,1,1,1,4,1,1,3,1
Éjjel a szigeten a kalózod többek között a kincseket kerested meg.,1,1,1,7,1,1,1,1,1,5,3,1,1,2,3
Ma ebédre a nagyi többek között mobiltelefont tálaltak fel.,1,1,1,1,1,1,1,1,1,2,4,1,1,3,1
Általában a szabók többek között citrommal ittuk ingeket.,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1
Tegnap este a gálán Miklós többek között Nórát döntöttem el.,1,1,1,1,1,1,1,1,1,1,3,1,2,5,1
"Most itt válassza ki a négyest, ez csak egy ellenörző kérdés.",4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Ki adja majd a könyveket gyerek nekik felnőtt nekik és oda ki?,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1
"Most ez mondat nincs jó, válaszolni kell egyes karika, jó?",1,3,1,1,1,1,1,1,1,1,1,1,1,1,1

In [19]:
# Turn the index column into a column called 'sentence', and reindex the df simply
df.reset_index(inplace=True)
df.rename(columns={'index': 'sentence'}, inplace=True)
df

,sentence,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Prolific ID:,5df2235d5a34251266ea645e,60245c7c3df42d131232cedb,695243059cda2a858a8374c8,5c48be0496d59b000183e68d,6a23d1de59ebe30c551cc503,6a4407786c0afee02f74e0d0,6150053fddd36a6892b8f13c,6932bf332627def0f1f8a46b,6a2d5bc0bd0691ccc75b8ce2,5a913d2cf0536100017196d8,5c69824b98f65b0001353794,61242dd5be1a06b174975a1f,693e69d41e0de9c8fad42703,5c66cc9246bfc200019044b8,608c08b442036ab091bbba75
1,Tegnap reggel Anna többek között egy banánt ev...,6,7,7,7,6,7,7,7,4,6,5,7,7,7,5
2,Tegnap reggel a kisfiú többek között egy ceruz...,6,7,7,7,5,7,7,7,6,7,5,7,7,6,7
3,Tegnap a műhelyben az asztalos többek között e...,6,7,7,7,7,7,7,7,6,6,5,7,7,7,7
4,Tavaly ilyenkor a katonaság többek között a he...,6,7,7,7,6,6,7,7,5,4,5,7,7,3,4
5,Tegnap este én többek között a fánkot sütöttem.,6,6,7,6,6,2,7,7,1,6,6,5,6,4,7
6,Hallottam hogy Éva többek között a tulipánt sz...,5,7,7,7,6,4,7,7,4,5,5,7,7,7,6
7,Tegnap este mi többek között ásványvizet vettünk.,6,7,7,5,4,5,7,6,3,5,5,6,7,2,7
8,Ma reggel Eszter többek között kávét ivott.,6,7,7,7,6,7,7,5,2,7,6,5,5,6,7
9,Régen az iskolában a diákok többek között néme...,3,7,7,7,7,7,7,6,4,5,5,6,7,3,7
10,Tavaly nyáron Marci többek között egy lepkét f...,5,7,7,7,4,6,7,7,3,6,6,6,6,7,2
11,Múlt hétvégén a turisták többek között egy rob...,4,7,7,6,4,3,7,7,5,6,6,5,3,6,7
12,Tíz évvel ez előtt a kertben a férfi többek kö...,1,7,6,6,6,6,7,7,3,5,5,4,7,4,7
13,Múltkor az állatkertben a gyerekek többek közö...,5,7,7,7,6,7,7,7,3,7,5,7,7,6,6
14,Múltkor a könyhában a szerelő többek között a ...,6,6,2,7,3,1,6,7,1,7,1,1,4,6,4
15,Éjjel a szigeten a kalóz többek között az aran...,2,6,7,7,3,5,7,7,3,5,5,7,6,6,3
16,Ma ebédre a nagyi többek között levest tálalt ...,1,7,7,7,6,7,7,7,3,7,6,6,7,2,7
17,Általában a műhelyben ez a szabó többek között...,3,4,2,6,6,1,5,1,3,3,1,2,4,3,4
18,Tegnap este a bálon Péter többek között Marit ...,6,7,6,6,6,3,7,7,6,5,6,7,7,6,7
19,Tegnap reggel Anna többek között nem egy nem k...,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1
20,Ki adja majd többek között a könyveket gyerek ...,1,2,1,1,1,1,1,1,1,1,1,1,1,2,1
21,Tegnap a reptéren az asztalos többek között cs...,4,1,2,4,1,4,1,1,1,6,6,3,3,5,1
22,Tavaly olyankor a hadsereg többek között az ös...,1,1,2,1,1,1,1,6,1,5,1,1,2,4,1
23,Tegnap este én többek között sok tankot sütöttem.,1,1,2,1,1,1,1,2,2,1,1,1,2,4,1
24,Hallottam hogy Magdi sok árvaházat ültetett a ...,1,1,2,1,1,1,1,1,2,2,3,1,1,3,1
25,Tegnap este mi többek között jegesmedvéket rep...,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1
26,Ma reggel Tilda többek között a kedvenc pincér...,1,1,2,1,1,1,1,1,1,2,2,1,3,2,1
27,Régen az iskolában a diákok többek között hold...,1,1,1,1,1,1,1,1,2,1,2,1,2,2,1
28,Tavaly nyáron Béla többek között orvosokat főz...,1,1,1,1,1,1,1,1,1,1,3,1,1,3,1
29,Múlt hétvégén az alpinisták többek között egy ...,1,1,1,1,1,1,1,1,1,2,2,1,1,7,1
30,Tíz évvel ez előtt a kertben a flamingó többek...,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1
31,Múltkor az cirkuszban a gyerekek többek között...,1,1,1,2,1,2,1,1,1,3,2,1,2,1,3
32,Múltkor a könyhában a szerelő többek között a ...,1,1,1,1,4,1,1,1,1,1,4,1,1,3,1
33,Éjjel a szigeten a kalózod többek között a kin...,1,1,1,7,1,1,1,1,1,5,3,1,1,2,3
34,Ma ebédre a nagyi többek között mobiltelefont ...,1,1,1,1,1,1,1,1,1,2,4,1,1,3,1
35,Általában a szabók többek között citrommal itt...,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1
36,Tegnap este a gálán Miklós többek között Nórát...,1,1,1,1,1,1,1,1,1,1,3,1,2,5,1
37,"Most itt válassza ki a négyest, ez csak egy el...",4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
38,Ki adja majd a könyveket gyerek nekik felnőtt ...,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1
39,"Most ez mondat nincs jó, válaszolni kell egyes...",1,3,1,1,1,1,1,1,1,1,1,1,1,1,1

In [20]:
# Read in the contrastive_sentences.xlsx for reference
reference_df = pd.read_excel('contrastive_sentences.xlsx')

# Preserve original `df` row order and add a `type` column where sentences match.
# This maps each sentence to its `type` value from the reference, leaving unmatched rows as NaN.
if 'sentence' in reference_df.columns and 'type' in reference_df.columns:
    type_map = reference_df.set_index('sentence')['type'].to_dict()
    df['type'] = df['sentence'].map(type_map)
    # ensure `type` is the last column
    cols = [c for c in df.columns if c != 'type'] + ['type']
    df = df[cols]
else:
    print("reference_df must contain 'sentence' and 'type' columns. Found:", reference_df.columns.tolist())

# show resulting frame
df

,sentence,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,type
0,Prolific ID:,5df2235d5a34251266ea645e,60245c7c3df42d131232cedb,695243059cda2a858a8374c8,5c48be0496d59b000183e68d,6a23d1de59ebe30c551cc503,6a4407786c0afee02f74e0d0,6150053fddd36a6892b8f13c,6932bf332627def0f1f8a46b,6a2d5bc0bd0691ccc75b8ce2,5a913d2cf0536100017196d8,5c69824b98f65b0001353794,61242dd5be1a06b174975a1f,693e69d41e0de9c8fad42703,5c66cc9246bfc200019044b8,608c08b442036ab091bbba75,NaN
1,Tegnap reggel Anna többek között egy banánt ev...,6,7,7,7,6,7,7,7,4,6,5,7,7,7,5,target
2,Tegnap reggel a kisfiú többek között egy ceruz...,6,7,7,7,5,7,7,7,6,7,5,7,7,6,7,target
3,Tegnap a műhelyben az asztalos többek között e...,6,7,7,7,7,7,7,7,6,6,5,7,7,7,7,target
4,Tavaly ilyenkor a katonaság többek között a he...,6,7,7,7,6,6,7,7,5,4,5,7,7,3,4,target
5,Tegnap este én többek között a fánkot sütöttem.,6,6,7,6,6,2,7,7,1,6,6,5,6,4,7,target
6,Hallottam hogy Éva többek között a tulipánt sz...,5,7,7,7,6,4,7,7,4,5,5,7,7,7,6,target
7,Tegnap este mi többek között ásványvizet vettünk.,6,7,7,5,4,5,7,6,3,5,5,6,7,2,7,target
8,Ma reggel Eszter többek között kávét ivott.,6,7,7,7,6,7,7,5,2,7,6,5,5,6,7,target
9,Régen az iskolában a diákok többek között néme...,3,7,7,7,7,7,7,6,4,5,5,6,7,3,7,target
10,Tavaly nyáron Marci többek között egy lepkét f...,5,7,7,7,4,6,7,7,3,6,6,6,6,7,2,target
11,Múlt hétvégén a turisták többek között egy rob...,4,7,7,6,4,3,7,7,5,6,6,5,3,6,7,target
12,Tíz évvel ez előtt a kertben a férfi többek kö...,1,7,6,6,6,6,7,7,3,5,5,4,7,4,7,target
13,Múltkor az állatkertben a gyerekek többek közö...,5,7,7,7,6,7,7,7,3,7,5,7,7,6,6,target
14,Múltkor a könyhában a szerelő többek között a ...,6,6,2,7,3,1,6,7,1,7,1,1,4,6,4,target
15,Éjjel a szigeten a kalóz többek között az aran...,2,6,7,7,3,5,7,7,3,5,5,7,6,6,3,target
16,Ma ebédre a nagyi többek között levest tálalt ...,1,7,7,7,6,7,7,7,3,7,6,6,7,2,7,target
17,Általában a műhelyben ez a szabó többek között...,3,4,2,6,6,1,5,1,3,3,1,2,4,3,4,target
18,Tegnap este a bálon Péter többek között Marit ...,6,7,6,6,6,3,7,7,6,5,6,7,7,6,7,target
19,Tegnap reggel Anna többek között nem egy nem k...,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,filler
20,Ki adja majd többek között a könyveket gyerek ...,1,2,1,1,1,1,1,1,1,1,1,1,1,2,1,filler
21,Tegnap a reptéren az asztalos többek között cs...,4,1,2,4,1,4,1,1,1,6,6,3,3,5,1,filler
22,Tavaly olyankor a hadsereg többek között az ös...,1,1,2,1,1,1,1,6,1,5,1,1,2,4,1,filler
23,Tegnap este én többek között sok tankot sütöttem.,1,1,2,1,1,1,1,2,2,1,1,1,2,4,1,filler
24,Hallottam hogy Magdi sok árvaházat ültetett a ...,1,1,2,1,1,1,1,1,2,2,3,1,1,3,1,filler
25,Tegnap este mi többek között jegesmedvéket rep...,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,filler
26,Ma reggel Tilda többek között a kedvenc pincér...,1,1,2,1,1,1,1,1,1,2,2,1,3,2,1,filler
27,Régen az iskolában a diákok többek között hold...,1,1,1,1,1,1,1,1,2,1,2,1,2,2,1,filler
28,Tavaly nyáron Béla többek között orvosokat főz...,1,1,1,1,1,1,1,1,1,1,3,1,1,3,1,filler
29,Múlt hétvégén az alpinisták többek között egy ...,1,1,1,1,1,1,1,1,1,2,2,1,1,7,1,filler
30,Tíz évvel ez előtt a kertben a flamingó többek...,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,filler
31,Múltkor az cirkuszban a gyerekek többek között...,1,1,1,2,1,2,1,1,1,3,2,1,2,1,3,filler
32,Múltkor a könyhában a szerelő többek között a ...,1,1,1,1,4,1,1,1,1,1,4,1,1,3,1,filler
33,Éjjel a szigeten a kalózod többek között a kin...,1,1,1,7,1,1,1,1,1,5,3,1,1,2,3,filler
34,Ma ebédre a nagyi többek között mobiltelefont ...,1,1,1,1,1,1,1,1,1,2,4,1,1,3,1,filler
35,Általában a szabók többek között citrommal itt...,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,filler
36,Tegnap este a gálán Miklós többek között Nórát...,1,1,1,1,1,1,1,1,1,1,3,1,2,5,1,filler
37,"Most itt válassza ki a négyest, ez csak egy el...",4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,attn
38,Ki adja majd a könyveket gyerek nekik felnőtt ...,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,attn
39,"Most ez mondat nincs jó, válaszolni kell egyes...",1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,attn

In [21]:
# Convert rating columns to numeric and calculate item-level statistics
rating_cols = [col for col in df.columns if col != "type"]

ratings = df[rating_cols].apply(pd.to_numeric, errors="coerce")

item_stats = pd.DataFrame({
    "mean": ratings.mean(axis=1),
    "sd": ratings.std(axis=1, ddof=1),
    "n": ratings.count(axis=1)
})

item_stats

        mean        sd   n
0        NaN       NaN   0
1   6.333333  0.975900  15
2   6.533333  0.743223  15
3   6.666667  0.617213  15
4   5.866667  1.355764  15
5   5.466667  1.807392  15
6   6.066667  1.162919  15
7   5.466667  1.552264  15
8   6.000000  1.362770  15
9   5.866667  1.505545  15
10  5.733333  1.579632  15
11  5.533333  1.457330  15
12  5.400000  1.764734  15
13  6.266667  1.162919  15
14  4.133333  2.445599  15
15  5.266667  1.751190  15
16  5.800000  2.042408  15
17  3.200000  1.656157  15
18  6.133333  1.060099  15
19  1.133333  0.516398  15
20  1.133333  0.351866  15
21  2.866667  1.884776  15
22  1.933333  1.667619  15
23  1.466667  0.833809  15
24  1.466667  0.743223  15
25  1.066667  0.258199  15
26  1.400000  0.632456  15
27  1.266667  0.457738  15
28  1.266667  0.703732  15
29  1.533333  1.552264  15
30  1.133333  0.516398  15
31  1.533333  0.743223  15
32  1.533333  1.125463  15
33  2.000000  1.812654  15
34  1.400000  0.910259  15
35  1.066667  0.258199  15
36  1.466667  1.125463  15
37  4.000000  0.000000  15
38  1.066667  0.258199  15
39  1.133333  0.516398  15

In [24]:
import plotly.express as px

plot_df = item_stats.reset_index().rename(columns={"index": "sentence"})
# drop the non-sentence metadata row and align sentence/type by row position
plot_df = plot_df.iloc[1:].reset_index(drop=True).copy()
plot_df["sentence"] = df["sentence"].iloc[1:].reset_index(drop=True).to_numpy()
plot_df["type"] = df["type"].iloc[1:].reset_index(drop=True).to_numpy()
plot_df["item"] = range(1, len(plot_df) + 1)

fig = px.scatter(
    plot_df,
    x="item",
    y="mean",
    color="type",
    error_y="sd",
    hover_data=["sentence", "mean", "sd", "n"],
    labels={
        "item": "Item",
        "mean": "Mean rating",
        "type": "Sentence type",
        "sd": "Standard deviation",
    },
    title="Mean Ratings by Sentence Type",
)

fig.update_traces(marker={"size": 9})
fig.update_layout(
    xaxis={"dtick": 1},
    yaxis={"range": [1, 7]},
)
fig.show()

# Export this as png
fig.write_image("mean_ratings_by_sentence_type.png")

In [25]:
# Calculate the mean and standard deviation of ratings for each sentence type
type_stats = plot_df.groupby("type").agg(
    mean=("mean", "mean"),
    sd=("sd", "std"),
)

# Print the targeted statistics for each sentence type
print("Target sentence type statistics:")
for sentence_type, stats in type_stats.iterrows():
    print(f"Type: {sentence_type}, Mean: {stats['mean']:.2f}, SD: {stats['sd']:.2f}")

Target sentence type statistics:
Type: attn, Mean: 2.07, SD: 0.26
Type: filler, Mean: 1.48, SD: 0.53
Type: target, Mean: 5.65, SD: 0.45