# Prolific demographics summary
Collect all exported demographic CSV files, keep only accepted participants, and compute age and gender summaries.

In [1]:
from pathlib import Path
import pandas as pd
import plotly.express as px

data_dir = Path("demographic_data")
csv_files = sorted(data_dir.glob("*.csv"))
if not csv_files:
    raise FileNotFoundError(f"No CSV files found in {data_dir.resolve()}")

raw = pd.concat((pd.read_csv(path) for path in csv_files), ignore_index=True)
raw.head()

,Submission id,Participant id,Status,Custom study tncs accepted at,Started at,Completed at,Reviewed at,Archived at,Time taken,Completion code,Total approvals,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status
0,68d137139fe16f73622b2536,61717173748006894b2b54ff,RETURNED,Not Applicable,NaN,NaN,NaN,2025-11-30T16:04:11.859308Z,NaN,NaN,1885,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
1,68d138b03c80804ac7f2915d,5c5b333a2b7de10001b78759,RETURNED,Not Applicable,2025-09-22T11:53:20.281000Z,NaN,NaN,2025-11-30T16:04:11.860833Z,NaN,NaN,403,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
2,68d13c9e2b874d16e9aaff36,5d5fac22e32d920001c82b53,RETURNED,Not Applicable,2025-09-22T12:10:06.266000Z,NaN,NaN,2025-11-30T16:04:11.861955Z,NaN,NaN,400,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
3,68d13d1b4c5ef3bdc1daf1d1,60245c7c3df42d131232cedb,RETURNED,Not Applicable,NaN,NaN,NaN,2025-11-30T16:04:11.864596Z,NaN,NaN,847,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
4,68d13e95b83dc7bbc8ab030a,615e9e6c4f37a1a03d73021b,RETURNED,Not Applicable,2025-09-22T12:18:29.720000Z,NaN,NaN,2025-11-30T16:04:11.863948Z,NaN,NaN,779,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED

In [2]:
raw

,Submission id,Participant id,Status,Custom study tncs accepted at,Started at,Completed at,Reviewed at,Archived at,Time taken,Completion code,Total approvals,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status
0,68d137139fe16f73622b2536,61717173748006894b2b54ff,RETURNED,Not Applicable,NaN,NaN,NaN,2025-11-30T16:04:11.859308Z,NaN,NaN,1885,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
1,68d138b03c80804ac7f2915d,5c5b333a2b7de10001b78759,RETURNED,Not Applicable,2025-09-22T11:53:20.281000Z,NaN,NaN,2025-11-30T16:04:11.860833Z,NaN,NaN,403,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
2,68d13c9e2b874d16e9aaff36,5d5fac22e32d920001c82b53,RETURNED,Not Applicable,2025-09-22T12:10:06.266000Z,NaN,NaN,2025-11-30T16:04:11.861955Z,NaN,NaN,400,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
3,68d13d1b4c5ef3bdc1daf1d1,60245c7c3df42d131232cedb,RETURNED,Not Applicable,NaN,NaN,NaN,2025-11-30T16:04:11.864596Z,NaN,NaN,847,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
4,68d13e95b83dc7bbc8ab030a,615e9e6c4f37a1a03d73021b,RETURNED,Not Applicable,2025-09-22T12:18:29.720000Z,NaN,NaN,2025-11-30T16:04:11.863948Z,NaN,NaN,779,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,693c417037da2b1b3f1d89dc,5f046bf88d2c186cc10c6ad0,APPROVED,Not Applicable,2025-12-12T16:23:20.422000Z,2025-12-12T17:29:31.198000Z,2025-12-13T20:15:31.166000Z,2025-12-12T17:54:56.197016Z,3971.0,NOCODE,36,40,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Unemployed (and job seeking)
201,693f6c0d793426856b6f92f4,61717173748006894b2b54ff,RETURNED,Not Applicable,NaN,NaN,NaN,2026-02-04T05:44:20.999127Z,NaN,NaN,2221,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
202,693fb5c8334778a3e2855a1e,693c768c138df103c91b6c22,APPROVED,Not Applicable,2025-12-15T07:16:35.685000Z,2025-12-15T07:38:13.471000Z,2026-01-05T00:00:35.742000Z,2025-12-15T07:38:13.812262Z,1298.0,CXOHLI21,0,33,Male,White,Hungary,Hungary,DATA_EXPIRED,Hungarian,No,Full-Time
203,693fc1aa86833ca38373d1bf,5f325435f0fc671a7434cabe,RETURNED,Not Applicable,2025-12-15T08:07:10.068000Z,NaN,NaN,2026-02-04T05:44:21.003130Z,NaN,NaN,1233,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
204,693fe07fd7b8f13d5b033519,6932b2822d8f41f447a6bb6b,APPROVED,Not Applicable,2025-12-15T10:18:49.956000Z,2025-12-15T10:35:44.386000Z,2026-01-05T00:00:36.078000Z,2025-12-15T10:35:44.970150Z,1015.0,CXOHLI21,1,34,Male,White,Hungary,Hungary,DATA_EXPIRED,Hungarian,No,Full-Time

In [3]:
accepted = (
    raw[raw["Status"].str.upper() == "APPROVED"]
    .assign(Age=lambda df: pd.to_numeric(df["Age"], errors="coerce"))
    .sort_values("Completed at")
    .drop_duplicates(subset="Participant id", keep="last")
    .reset_index(drop=True)
 )
accepted[["Participant id", "Status", "Age", "Sex"]].head()

             Participant id    Status  Age     Sex
0  60d26e7cd9f0761e4d12b9f8  APPROVED   25  Female
1  6151b07ac0d164fdd7e53100  APPROVED   24    Male
2  5f338ba6ea047119dbd6e49e  APPROVED   30    Male
3  6154d933a58bf7bcd9e81fed  APPROVED   38  Female
4  5d4fe6a2ffbcf800019d5e54  APPROVED   59  Female

In [4]:
accepted

,Submission id,Participant id,Status,Custom study tncs accepted at,Started at,Completed at,Reviewed at,Archived at,Time taken,Completion code,Total approvals,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status
0,68d172ee4f15faf3af4b65bb,60d26e7cd9f0761e4d12b9f8,APPROVED,Not Applicable,2025-09-22T16:02:34.414000Z,2025-09-22T16:34:08.982000Z,2025-09-23T04:30:20.403000Z,2025-09-22T16:34:09.540159Z,1895.0,C1KD1A87,396,25,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Unemployed (and job seeking)
1,68d420ac46fbb9d655509cd3,6151b07ac0d164fdd7e53100,APPROVED,Not Applicable,2025-09-24T16:47:44.443000Z,2025-09-24T17:17:29.766000Z,2025-09-29T10:34:54.432000Z,2025-09-24T17:17:30.315398Z,1786.0,C1KD1A87,435,24,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Full-Time
2,68d4dadf28acf5ed2002e78e,5f338ba6ea047119dbd6e49e,APPROVED,Not Applicable,2025-09-25T06:02:14.558000Z,2025-09-25T06:26:06.654000Z,2025-09-29T10:36:36.118000Z,2025-09-25T06:26:07.207621Z,1433.0,C1KD1A87,731,30,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
3,68d506fd0942a8cc7be8f620,6154d933a58bf7bcd9e81fed,APPROVED,Not Applicable,2025-09-25T09:10:21.033000Z,2025-09-25T09:33:36.530000Z,2025-09-29T10:36:36.639000Z,2025-09-25T09:33:36.923566Z,1396.0,C1KD1A87,28,38,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
4,68d56fa02d94f86ab37cb981,5d4fe6a2ffbcf800019d5e54,APPROVED,Not Applicable,2025-09-25T16:39:49.125000Z,2025-09-25T17:42:29.717000Z,2025-09-29T10:36:36.972000Z,2025-09-25T17:42:30.130330Z,3761.0,C1KD1A87,312,59,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
5,68d6433e8e991f0f0bde9f92,61545727036ae019fdeea5df,APPROVED,Not Applicable,2025-09-26T07:39:42.978000Z,2025-09-26T07:58:01.662000Z,2025-09-29T10:36:37.500000Z,2025-09-26T07:58:02.099723Z,1099.0,C1KD1A87,231,32,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
6,68d666ab793d70371d265341,6108da57e362f96a3ee32a88,APPROVED,Not Applicable,2025-09-26T10:11:03.697000Z,2025-09-26T10:29:49.671000Z,2025-09-29T10:38:20.699000Z,2025-09-26T10:29:50.117097Z,1126.0,C1KD1A87,95,27,Female,White,Romania,Hungary,Hungary,Hungarian,No,Full-Time
7,68d80cd01c298d02d32b5e75,5f99dc8aa866bf0bf2d60f46,APPROVED,Not Applicable,2025-09-27T16:13:44.885000Z,2025-09-27T17:00:17.566000Z,2025-09-29T12:24:24.990000Z,2025-09-27T17:00:18.079070Z,2793.0,NOCODE,798,23,Male,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
8,68da700b3abf8bd08b473189,5ee75f3d1a88450293a38aeb,APPROVED,Not Applicable,2025-09-29T11:43:04.054000Z,2025-09-29T12:26:01.832000Z,2025-10-02T04:36:08.773000Z,2025-09-29T12:26:02.292511Z,2578.0,C1KD1A87,442,40,Male,White,Hungary,United Kingdom,Hungary,Hungarian,No,Full-Time
9,68daed82d15d2f5ccfa1ce96,666d9692dac9d55d3f331401,APPROVED,Not Applicable,2025-09-29T20:35:41.106000Z,2025-09-29T20:57:02.163000Z,2025-10-02T04:36:25.663000Z,2025-09-29T20:57:11.487652Z,1282.0,C1KD1A87,704,34,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,No,Full-Time
10,68db94eb3da3577c0e177679,641379405684937e6fad9f1b,APPROVED,Not Applicable,2025-09-30T08:29:36.413000Z,2025-09-30T09:00:34.580000Z,2025-10-02T05:00:22.357000Z,2025-09-30T09:00:35.089840Z,1859.0,C1KD1A87,351,36,Female,White,Hungary,United Kingdom,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
11,68dbb963ed94e22de931a7f2,5e1cabad3b577b000c55e660,APPROVED,Not Applicable,2025-09-30T11:08:16.430000Z,2025-09-30T12:02:53.999000Z,2025-10-02T05:06:07.829000Z,2025-09-30T12:02:54.381245Z,3278.0,NOCODE,750,23,Male,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
12,68dc195ad7aa9566543d4d3b,5dade76a4860f70017f70ec5,APPROVED,Not Applicable,2025-09-30T17:54:36.333000Z,2025-09-30T18:07:12.487000Z,2025-10-02T04:46:50.249000Z,2025-09-30T18:07:16.320768Z,757.0,C1KD1A87,680,23,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,DATA_EXPIRED
13,68dd93342d2c62ec1dc992d6,6658c355ad6d072d4f208486,APPROVED,Not Applicable,2025-10-01T20:46:52.688000Z,2025-10-01T21:17:57.371000Z,2025-10-02T04:47:20.206000Z,2025-10-01T21:17:57.806495Z,1865.0,C1KD1A87,23,40,Female,White,Hungary,United Kingdom,Hungary,Hungarian,No,Full-Time
14,68dd813139d45bce721d9288,642b35c70771761602e9c3ae,APPROVED,Not Applicable,2025-10-01T19:29:53.060000Z,2025-10-01T21:50:21.518000Z,2025-10-03T04:16:30.609000Z,2025-10-01T21:50:23.155171Z,8429.0,C1KD1A87,151,54,Male,White,Romania,United Kingdom,Hungary,Hungarian,No,Full-Time
15,68e3b088bd169f1cafecf257,5f9bfbae0517c60102da9e57,APPROVED,Not Applicable,2025-10-06T12:05:28.599000Z,2025-10-06T12:30:55.593000Z,2025-10-13T08:20:45.494000Z,2025-10-06T12:30:55.975424Z,1527.0,CXOHLI21,179,32,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Part-Time
16,68e4266f5c0c6b68c3d0ea5e,5b93d1913dca6000012c5fdc,APPROVED,Not Applicable,2025-10-06T20:28:31.749000Z,2025-10-06T21:02:14.087000Z,2025-10-13T08:29:44.981000Z,2025-10-06T21:02:59.849432Z,2023.0,CXOHLI21,548,33,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
17,68e4d4b3ae601e04fb319e33,5c5c785fc9735b00010ced0b,APPROVED,Not Applicable,2025-10-07T08:52:12.307000Z,2025-10-07T09:30:33.869000Z,2025-10-13T08:20:45.789000Z,2025-10-07T09:30:34.296579Z,2302.0,CXOHLI21,298,38,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
18,68e6481673ca660abee9b28d,59679c319febf80001d53655,APPROVED,Not Applicable,2025-10-08T11:19:53.171000Z,2025-10-08T11:45:15.334000Z,2025-10-13T08:20:46.059000Z,2025-10-08T11:45:15.953927Z,1523.0,CXOHLI21,233,30,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
19,68e77e35026a3c24fb5becd4,615d5311a9fbf1f98aa62a5a,APPROVED,Not Applicable,2025-10-09T09:20:58.525000Z,2025-10-09T09:53:00.595000Z,2025-10-13T08:24:18.247000Z,2025-10-09T09:53:01.585565Z,1923.0,CXOHLI21,559,26,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Full-Time
20,68e8d48d67e1b417ccd9f200,5f3ce934a12769b771503625,APPROVED,Not Applicable,2025-10-10T09:40:29.309000Z,2025-10-10T10:19:33.237000Z,2025-10-13T08:29:46.522000Z,2025-10-10T10:20:43.018160Z,2344.0,CXOHLI21,158,50,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,DATA_EXPIRED,DATA_EXPIRED
21,68e8f8c7c43a314a86496d4d,60fd4fbf1a3f1446d576e5d4,APPROVED,Not Applicable,2025-10-10T12:15:15.484000Z,2025-10-10T12:38:46.078000Z,2025-10-13T08:29:46.799000Z,2025-10-10T12:38:48.364125Z,1411.0,CXOHLI21,124,34,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
22,68e907aabed114f300350ecb,5f5fc58bfcb0db07c6c64d9e,APPROVED,Not Applicable,2025-10-10T13:18:38.525000Z,2025-10-10T13:53:18.136000Z,2025-10-13T08:24:18.502000Z,2025-10-10T13:53:18.725048Z,2080.0,CXOHLI21,1315,52,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,DATA_EXPIRED,DATA_EXPIRED
23,68e96a33c7ee1e58e3190247,667f230c31ae00d966dfff6e,APPROVED,Not Applicable,2025-10-10T20:19:03.886000Z,2025-10-10T20:41:20.805000Z,2025-10-13T08:24:18.746000Z,2025-10-10T20:41:21.231520Z,1337.0,CXOHLI21,214,40,Male,White,Hungary,United Kingdom,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
24,68ed2784211b60d0d993dfb3,60d0e99c4a61ffe6c5703250,APPROVED,Not Applicable,2025-10-13T16:23:36.731000Z,2025-10-13T16:49:37.742000Z,2025-10-18T11:12:28.180000Z,2025-10-13T16:49:43.080145Z,1562.0,CXOHLI21,121,37,Female,White,Romania,United Kingdom,Romania,Hungarian,No,Full-Time
25,68f38a88e3add432729abc13,61242dd5be1a06b174975a1f,APPROVED,Not Applicable,2025-10-18T12:39:36.624000Z,2025-10-18T13:04:15.197000Z,2025-10-18T16:03:17.966000Z,2025-10-18T13:04:24.633038Z,1479.0,CXOHLI21,466,23,Female,White,Hungary,Hungary,Hungary,Hungarian,Yes,Other
26,692e8d64abff0396644c7b26,6153fe02f96d83a510c3c92b,APPROVED,Not Applicable,2025-12-02T06:56:26.440000Z,2025-12-02T07:39:30.484000Z,2025-12-13T18:14:08.559000Z,2025-12-02T07:39:30.847763Z,2585.0,CXOHLI21,613,43,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
27,6932c6a816128a5ae5211d7d,6932924be6c91fad3d38ca24,APPROVED,Not Applicable,2025-12-05T11:49:00.755000Z,2025-12-05T12:09:33.087000Z,2025-12-13T18:15:30.356000Z,2025-12-05T12:09:33.529291Z,1233.0,CXOHLI21,0,31,Female,White,Hungary,United Kingdom,Hungary,Hungarian,No,Full-Time
28,693317d98f58740fd983c562,60ed917a71051ceb8ec151c9,APPROVED,Not Applicable,2025-12-05T17:35:25.756000Z,2025-12-05T18:04:56.301000Z,2025-12-13T18:15:44.423000Z,2025-12-05T18:04:56.706049Z,1771.0,There was no completion code,45,24,Prefer not to say,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
29,693344c9773918fd0bbdb177,5bbc9e8c70f8df0001c0e060,APPROVED,Not Applicable,2025-12-05T20:47:10.111000Z,2025-12-05T21:06:50.037000Z,2025-12-13T18:15:55.662000Z,2025-12-05T21:06:50.405883Z,1180.0,CXOHLI21,128,51,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
30,6935b9a4e2664577b61d37ed,60fc8070ac259dd44fb94150,APPROVED,Not Applicable,2025-12-07T17:30:12.873000Z,2025-12-07T17:46:21.099000Z,2025-12-13T18:16:18.212000Z,2025-12-07T17:46:21.472031Z,969.0,CXOHLI21,427,28,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,Full-Time
31,6936cb7c1b42374beeef8949,5909f8b6bc185d00011aa307,APPROVED,Not Applicable,2025-12-08T12:58:41.278000Z,2025-12-08T13:22:24.017000Z,2025-12-13T17:09:30.877000Z,2025-12-08T13:22:24.365415Z,1423.0,CXOHLI21,542,39,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
32,69371570ae153da0e23fb557,5ff48ac68fd71dba8aab240c,APPROVED,Not Applicable,2025-12-08T18:14:08.864000Z,2025-12-08T18:30:59.252000Z,2025-12-13T17:09:47.298000Z,2025-12-08T18:30:59.597934Z,1011.0,CXOHLI21,17,51,Female,DATA_EXPIRED,Hungary,United Kingdom,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
33,6937251dcdd887b9b7d42bd8,5f4c042383588080d02e61a3,APPROVED,Not Applicable,2025-12-08T19:28:00.421000Z,2025-12-08T20:23:07.922000Z,2025-12-13T17:10:00.562000Z,2025-12-08T20:23:08.268515Z,3308.0,CXOHLI21,426,25,Female,White,Hungary,Hungary,Hungary,Hungarian,Yes,Full-Time
34,6937e1bbcdc7fab4f5cd70c0,691bc10f288fd6bed229f5bb,APPROVED,Not Applicable,2025-12-09T08:45:47.710000Z,2025-12-09T09:05:19.884000Z,2025-12-13T17:10:48.410000Z,2025-12-09T09:05:20.223561Z,1173.0,CXOHLI21,3,44,Female,White,Hungary,Israel,Israel,Hungarian,No,Part-Time
35,6939450f4098cd730abb816c,6150053fddd36a6892b8f13c,APPROVED,Not Applicable,2025-12-10T10:01:56.086000Z,2025-12-10T10:15:31.261000Z,2025-12-13T18:20:51.488000Z,2025-12-10T10:15:31.619381Z,816.0,CXOHLI21,605,49,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
36,693944dc5cef0971cb0416df,69346587dfdffc1057144d32,APPROVED,Not Applicable,2025-12-10T10:02:47.691000Z,2025-12-10T10:32:39.947000Z,2025-12-13T18:21:05.864000Z,2025-12-10T10:32:40.273221Z,1793.0,CXOHLI21,2,21,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Unemployed (and job seeking)
37,693945bfcdf3d1e39f7c47bb,67698e94c727a4a942390c57,APPROVED,Not Applicable,2025-12-10T10:04:51.895000Z,2025-12-10T10:35:48.442000Z,2025-12-13T18:22:04.620000Z,2025-12-10T10:36:09.616130Z,1857.0,CXOHLI21,1487,61,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,DATA_EXPIRED,DATA_EXPIRED
38,69394f2196b78664394073c4,5f4e8bbd350d2a08d6175762,APPROVED,Not Applicable,2025-12-10T10:44:54.204000Z,2025-12-10T10:59:17.093000Z,2025-12-13T18:27:40.735000Z,2025-12-10T10:59:26.539762Z,863.0,CXOHLI21,176,34,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
39,6939503bc782277bfb52e131,69262c7d3bf2812cd35a933d,APPROVED,Not Applicable,2025-12-10T10:49:37.605000Z,2025-12-10T11:05:44.325000Z,2025-12-13T18:49:48.965000Z,2025-12-10T11:05:44.685500Z,967.0,CXOHLI21,12,33,Female,White,Hungary,Netherlands,Hungary,Hungarian,No,Unemployed (and job seeking)
40,693954e07fef04ab2b207b0e,5f3013e31c8a690aacb02c31,APPROVED,Not Applicable,2025-12-10T11:09:28.404000Z,2025-12-10T11:43:41.240000Z,2025-12-13T18:50:04.654000Z,2025-12-10T11:43:41.686657Z,2053.0,CXOHLI21,2514,33,Female,White,Hungary,United Kingdom,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
41,69396d9d0776dd10f09f06ff,604dedd2805fe682c5bc51c0,APPROVED,Not Applicable,2025-12-10T12:54:58.179000Z,2025-12-10T13:15:03.999000Z,2025-12-13T18:50:18.793000Z,2025-12-10T13:15:04.318507Z,1206.0,CXOHLI21,829,41,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
42,69398e7c88dbe3546e02861e,6932be225beb1292d32a80c0,APPROVED,Not Applicable,2025-12-10T15:15:14.273000Z,2025-12-10T15:35:36.457000Z,2025-12-13T17:11:47.621000Z,2025-12-10T15:35:36.803282Z,1223.0,CXOHLI21,1,20,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Part-Time
43,6939b5cd140ecb6c99922480,63d7b1d1d1cba5b706f4004d,APPROVED,Not Applicable,2025-12-10T18:02:53.646000Z,2025-12-10T18:25:26.815000Z,2025-12-13T18:17:20.797000Z,2025-12-10T18:25:27.162358Z,1354.0,CXOHLI21,5,37,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,No,Part-Time
44,6939bdb102f86650672d9272,60eeb5c2667ce4a8a80521c9,APPROVED,Not Applicable,2025-12-10T18:36:40.865000Z,2025-12-10T18:58:41.101000Z,2025-12-15T01:50:52.822000Z,2025-12-10T18:58:41.449986Z,1321.0,NOCODE,38,23,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Part-Time
45,6939eff6910dc57b2b4a7980,60cb4cd6477b2ff7c1adaea4,APPROVED,Not Applicable,2025-12-10T22:11:11.117000Z,2025-12-10T22:26:21.878000Z,2025-12-13T20:12:25.079000Z,2025-12-10T22:26:22.221917Z,911.0,CXOHLI21,557,37,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
46,693a7cd9737f56a416655d43,610bfb5a1da99c3da6313a50,APPROVED,Not Applicable,2025-12-11T08:12:13.884000Z,2025-12-11T08:30:46.508000Z,2025-12-13T20:14:34.728000Z,2025-12-11T08:30:46.844196Z,1113.0,CXOHLI21,191,44,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
47,693ab70296bf45483d4c6599,5cb9d45ac3eb6a00123c226e,APPROVED,Not Applicable,2025-12-11T12:20:22.373000Z,2025-12-11T12:45:12.462000Z,2025-12-13T20:14:48.646000Z,2025-12-11T12:45:12.800556Z,1491.0,CXOHLI21,491,32,Male,White,Latvia,United Kingdom,Latvia,Hungarian,No,Full-Time
48,693ab58dc900277730a2e9aa,6932c07f41479348b6b5d9fb,APPROVED,Not Applicable,2025-12-11T12:16:38.367000Z,2025-12-11T13:10:20.425000Z,2025-12-13T18:12:08.184000Z,2025-12-11T13:10:20.975831Z,3223.0,CXOHLI21,1,25,Female,Mixed,Hungary,Hungary,Hungary,Hungarian,Yes,Unemployed (and job seeking)
49,693b0303ec4254db0f80cbcc,5e3b29dc87243b34bde5abfa,APPROVED,Not Applicable,2025-12-11T17:47:14.784000Z,2025-12-11T18:00:46.492000Z,2025-12-13T20:15:00.629000Z,2025-12-11T18:00:46.853630Z,812.0,CXOHLI21,620,47,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Unemployed (and job seeking)
50,693b115bdc02110dbce568cb,6153ff2b2d71a6a4c3789a93,APPROVED,Not Applicable,2025-12-11T18:45:50.145000Z,2025-12-11T18:59:52.876000Z,2025-12-13T20:15:12.858000Z,2025-12-11T18:59:53.256886Z,843.0,CXOHLI21,317,48,Male,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
51,693c417037da2b1b3f1d89dc,5f046bf88d2c186cc10c6ad0,APPROVED,Not Applicable,2025-12-12T16:23:20.422000Z,2025-12-12T17:29:31.198000Z,2025-12-13T20:15:31.166000Z,2025-12-12T17:54:56.197016Z,3971.0,NOCODE,36,40,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Unemployed (and job seeking)
52,693d14957377b084c6d3554e,693d10ff23f42886b9051c5f,APPROVED,Not Applicable,2025-12-13T07:24:15.764000Z,2025-12-13T07:56:32.984000Z,2025-12-13T18:17:31.505000Z,2025-12-13T07:56:33.518200Z,1938.0,NOCODE,0,21,Female,White,Serbia,Hungary,DATA_EXPIRED,Hungarian,Yes,Part-Time
53,693fb5c8334778a3e2855a1e,693c768c138df103c91b6c22,APPROVED,Not Applicable,2025-12-15T07:16:35.685000Z,2025-12-15T07:38:13.471000Z,2026-01-05T00:00:35.742000Z,2025-12-15T07:38:13.812262Z,1298.0,CXOHLI21,0,33,Male,White,Hungary,Hungary,DATA_EXPIRED,Hungarian,No,Full-Time
54,693fe07fd7b8f13d5b033519,6932b2822d8f41f447a6bb6b,APPROVED,Not Applicable,2025-12-15T10:18:49.956000Z,2025-12-15T10:35:44.386000Z,2026-01-05T00:00:36.078000Z,2025-12-15T10:35:44.970150Z,1015.0,CXOHLI21,1,34,Male,White,Hungary,Hungary,DATA_EXPIRED,Hungarian,No,Full-Time

In [5]:
list_of_participants_to_remove = ['642b35c70771761602e9c3ae', '641379405684937e6fad9f1b', '5f046bf88d2c186cc10c6ad0']
accepted = accepted[~accepted["Participant id"].isin(list_of_participants_to_remove)].reset_index(drop=True)

In [6]:
accepted

,Submission id,Participant id,Status,Custom study tncs accepted at,Started at,Completed at,Reviewed at,Archived at,Time taken,Completion code,Total approvals,Age,Sex,Ethnicity simplified,Country of birth,Country of residence,Nationality,Language,Student status,Employment status
0,68d172ee4f15faf3af4b65bb,60d26e7cd9f0761e4d12b9f8,APPROVED,Not Applicable,2025-09-22T16:02:34.414000Z,2025-09-22T16:34:08.982000Z,2025-09-23T04:30:20.403000Z,2025-09-22T16:34:09.540159Z,1895.0,C1KD1A87,396,25,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Unemployed (and job seeking)
1,68d420ac46fbb9d655509cd3,6151b07ac0d164fdd7e53100,APPROVED,Not Applicable,2025-09-24T16:47:44.443000Z,2025-09-24T17:17:29.766000Z,2025-09-29T10:34:54.432000Z,2025-09-24T17:17:30.315398Z,1786.0,C1KD1A87,435,24,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Full-Time
2,68d4dadf28acf5ed2002e78e,5f338ba6ea047119dbd6e49e,APPROVED,Not Applicable,2025-09-25T06:02:14.558000Z,2025-09-25T06:26:06.654000Z,2025-09-29T10:36:36.118000Z,2025-09-25T06:26:07.207621Z,1433.0,C1KD1A87,731,30,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
3,68d506fd0942a8cc7be8f620,6154d933a58bf7bcd9e81fed,APPROVED,Not Applicable,2025-09-25T09:10:21.033000Z,2025-09-25T09:33:36.530000Z,2025-09-29T10:36:36.639000Z,2025-09-25T09:33:36.923566Z,1396.0,C1KD1A87,28,38,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
4,68d56fa02d94f86ab37cb981,5d4fe6a2ffbcf800019d5e54,APPROVED,Not Applicable,2025-09-25T16:39:49.125000Z,2025-09-25T17:42:29.717000Z,2025-09-29T10:36:36.972000Z,2025-09-25T17:42:30.130330Z,3761.0,C1KD1A87,312,59,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
5,68d6433e8e991f0f0bde9f92,61545727036ae019fdeea5df,APPROVED,Not Applicable,2025-09-26T07:39:42.978000Z,2025-09-26T07:58:01.662000Z,2025-09-29T10:36:37.500000Z,2025-09-26T07:58:02.099723Z,1099.0,C1KD1A87,231,32,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
6,68d666ab793d70371d265341,6108da57e362f96a3ee32a88,APPROVED,Not Applicable,2025-09-26T10:11:03.697000Z,2025-09-26T10:29:49.671000Z,2025-09-29T10:38:20.699000Z,2025-09-26T10:29:50.117097Z,1126.0,C1KD1A87,95,27,Female,White,Romania,Hungary,Hungary,Hungarian,No,Full-Time
7,68d80cd01c298d02d32b5e75,5f99dc8aa866bf0bf2d60f46,APPROVED,Not Applicable,2025-09-27T16:13:44.885000Z,2025-09-27T17:00:17.566000Z,2025-09-29T12:24:24.990000Z,2025-09-27T17:00:18.079070Z,2793.0,NOCODE,798,23,Male,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
8,68da700b3abf8bd08b473189,5ee75f3d1a88450293a38aeb,APPROVED,Not Applicable,2025-09-29T11:43:04.054000Z,2025-09-29T12:26:01.832000Z,2025-10-02T04:36:08.773000Z,2025-09-29T12:26:02.292511Z,2578.0,C1KD1A87,442,40,Male,White,Hungary,United Kingdom,Hungary,Hungarian,No,Full-Time
9,68daed82d15d2f5ccfa1ce96,666d9692dac9d55d3f331401,APPROVED,Not Applicable,2025-09-29T20:35:41.106000Z,2025-09-29T20:57:02.163000Z,2025-10-02T04:36:25.663000Z,2025-09-29T20:57:11.487652Z,1282.0,C1KD1A87,704,34,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,No,Full-Time
10,68dbb963ed94e22de931a7f2,5e1cabad3b577b000c55e660,APPROVED,Not Applicable,2025-09-30T11:08:16.430000Z,2025-09-30T12:02:53.999000Z,2025-10-02T05:06:07.829000Z,2025-09-30T12:02:54.381245Z,3278.0,NOCODE,750,23,Male,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
11,68dc195ad7aa9566543d4d3b,5dade76a4860f70017f70ec5,APPROVED,Not Applicable,2025-09-30T17:54:36.333000Z,2025-09-30T18:07:12.487000Z,2025-10-02T04:46:50.249000Z,2025-09-30T18:07:16.320768Z,757.0,C1KD1A87,680,23,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,DATA_EXPIRED
12,68dd93342d2c62ec1dc992d6,6658c355ad6d072d4f208486,APPROVED,Not Applicable,2025-10-01T20:46:52.688000Z,2025-10-01T21:17:57.371000Z,2025-10-02T04:47:20.206000Z,2025-10-01T21:17:57.806495Z,1865.0,C1KD1A87,23,40,Female,White,Hungary,United Kingdom,Hungary,Hungarian,No,Full-Time
13,68e3b088bd169f1cafecf257,5f9bfbae0517c60102da9e57,APPROVED,Not Applicable,2025-10-06T12:05:28.599000Z,2025-10-06T12:30:55.593000Z,2025-10-13T08:20:45.494000Z,2025-10-06T12:30:55.975424Z,1527.0,CXOHLI21,179,32,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Part-Time
14,68e4266f5c0c6b68c3d0ea5e,5b93d1913dca6000012c5fdc,APPROVED,Not Applicable,2025-10-06T20:28:31.749000Z,2025-10-06T21:02:14.087000Z,2025-10-13T08:29:44.981000Z,2025-10-06T21:02:59.849432Z,2023.0,CXOHLI21,548,33,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
15,68e4d4b3ae601e04fb319e33,5c5c785fc9735b00010ced0b,APPROVED,Not Applicable,2025-10-07T08:52:12.307000Z,2025-10-07T09:30:33.869000Z,2025-10-13T08:20:45.789000Z,2025-10-07T09:30:34.296579Z,2302.0,CXOHLI21,298,38,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
16,68e6481673ca660abee9b28d,59679c319febf80001d53655,APPROVED,Not Applicable,2025-10-08T11:19:53.171000Z,2025-10-08T11:45:15.334000Z,2025-10-13T08:20:46.059000Z,2025-10-08T11:45:15.953927Z,1523.0,CXOHLI21,233,30,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
17,68e77e35026a3c24fb5becd4,615d5311a9fbf1f98aa62a5a,APPROVED,Not Applicable,2025-10-09T09:20:58.525000Z,2025-10-09T09:53:00.595000Z,2025-10-13T08:24:18.247000Z,2025-10-09T09:53:01.585565Z,1923.0,CXOHLI21,559,26,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Full-Time
18,68e8d48d67e1b417ccd9f200,5f3ce934a12769b771503625,APPROVED,Not Applicable,2025-10-10T09:40:29.309000Z,2025-10-10T10:19:33.237000Z,2025-10-13T08:29:46.522000Z,2025-10-10T10:20:43.018160Z,2344.0,CXOHLI21,158,50,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,DATA_EXPIRED,DATA_EXPIRED
19,68e8f8c7c43a314a86496d4d,60fd4fbf1a3f1446d576e5d4,APPROVED,Not Applicable,2025-10-10T12:15:15.484000Z,2025-10-10T12:38:46.078000Z,2025-10-13T08:29:46.799000Z,2025-10-10T12:38:48.364125Z,1411.0,CXOHLI21,124,34,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
20,68e907aabed114f300350ecb,5f5fc58bfcb0db07c6c64d9e,APPROVED,Not Applicable,2025-10-10T13:18:38.525000Z,2025-10-10T13:53:18.136000Z,2025-10-13T08:24:18.502000Z,2025-10-10T13:53:18.725048Z,2080.0,CXOHLI21,1315,52,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,DATA_EXPIRED,DATA_EXPIRED
21,68e96a33c7ee1e58e3190247,667f230c31ae00d966dfff6e,APPROVED,Not Applicable,2025-10-10T20:19:03.886000Z,2025-10-10T20:41:20.805000Z,2025-10-13T08:24:18.746000Z,2025-10-10T20:41:21.231520Z,1337.0,CXOHLI21,214,40,Male,White,Hungary,United Kingdom,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
22,68ed2784211b60d0d993dfb3,60d0e99c4a61ffe6c5703250,APPROVED,Not Applicable,2025-10-13T16:23:36.731000Z,2025-10-13T16:49:37.742000Z,2025-10-18T11:12:28.180000Z,2025-10-13T16:49:43.080145Z,1562.0,CXOHLI21,121,37,Female,White,Romania,United Kingdom,Romania,Hungarian,No,Full-Time
23,68f38a88e3add432729abc13,61242dd5be1a06b174975a1f,APPROVED,Not Applicable,2025-10-18T12:39:36.624000Z,2025-10-18T13:04:15.197000Z,2025-10-18T16:03:17.966000Z,2025-10-18T13:04:24.633038Z,1479.0,CXOHLI21,466,23,Female,White,Hungary,Hungary,Hungary,Hungarian,Yes,Other
24,692e8d64abff0396644c7b26,6153fe02f96d83a510c3c92b,APPROVED,Not Applicable,2025-12-02T06:56:26.440000Z,2025-12-02T07:39:30.484000Z,2025-12-13T18:14:08.559000Z,2025-12-02T07:39:30.847763Z,2585.0,CXOHLI21,613,43,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
25,6932c6a816128a5ae5211d7d,6932924be6c91fad3d38ca24,APPROVED,Not Applicable,2025-12-05T11:49:00.755000Z,2025-12-05T12:09:33.087000Z,2025-12-13T18:15:30.356000Z,2025-12-05T12:09:33.529291Z,1233.0,CXOHLI21,0,31,Female,White,Hungary,United Kingdom,Hungary,Hungarian,No,Full-Time
26,693317d98f58740fd983c562,60ed917a71051ceb8ec151c9,APPROVED,Not Applicable,2025-12-05T17:35:25.756000Z,2025-12-05T18:04:56.301000Z,2025-12-13T18:15:44.423000Z,2025-12-05T18:04:56.706049Z,1771.0,There was no completion code,45,24,Prefer not to say,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
27,693344c9773918fd0bbdb177,5bbc9e8c70f8df0001c0e060,APPROVED,Not Applicable,2025-12-05T20:47:10.111000Z,2025-12-05T21:06:50.037000Z,2025-12-13T18:15:55.662000Z,2025-12-05T21:06:50.405883Z,1180.0,CXOHLI21,128,51,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
28,6935b9a4e2664577b61d37ed,60fc8070ac259dd44fb94150,APPROVED,Not Applicable,2025-12-07T17:30:12.873000Z,2025-12-07T17:46:21.099000Z,2025-12-13T18:16:18.212000Z,2025-12-07T17:46:21.472031Z,969.0,CXOHLI21,427,28,Female,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,Full-Time
29,6936cb7c1b42374beeef8949,5909f8b6bc185d00011aa307,APPROVED,Not Applicable,2025-12-08T12:58:41.278000Z,2025-12-08T13:22:24.017000Z,2025-12-13T17:09:30.877000Z,2025-12-08T13:22:24.365415Z,1423.0,CXOHLI21,542,39,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
30,69371570ae153da0e23fb557,5ff48ac68fd71dba8aab240c,APPROVED,Not Applicable,2025-12-08T18:14:08.864000Z,2025-12-08T18:30:59.252000Z,2025-12-13T17:09:47.298000Z,2025-12-08T18:30:59.597934Z,1011.0,CXOHLI21,17,51,Female,DATA_EXPIRED,Hungary,United Kingdom,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
31,6937251dcdd887b9b7d42bd8,5f4c042383588080d02e61a3,APPROVED,Not Applicable,2025-12-08T19:28:00.421000Z,2025-12-08T20:23:07.922000Z,2025-12-13T17:10:00.562000Z,2025-12-08T20:23:08.268515Z,3308.0,CXOHLI21,426,25,Female,White,Hungary,Hungary,Hungary,Hungarian,Yes,Full-Time
32,6937e1bbcdc7fab4f5cd70c0,691bc10f288fd6bed229f5bb,APPROVED,Not Applicable,2025-12-09T08:45:47.710000Z,2025-12-09T09:05:19.884000Z,2025-12-13T17:10:48.410000Z,2025-12-09T09:05:20.223561Z,1173.0,CXOHLI21,3,44,Female,White,Hungary,Israel,Israel,Hungarian,No,Part-Time
33,6939450f4098cd730abb816c,6150053fddd36a6892b8f13c,APPROVED,Not Applicable,2025-12-10T10:01:56.086000Z,2025-12-10T10:15:31.261000Z,2025-12-13T18:20:51.488000Z,2025-12-10T10:15:31.619381Z,816.0,CXOHLI21,605,49,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
34,693944dc5cef0971cb0416df,69346587dfdffc1057144d32,APPROVED,Not Applicable,2025-12-10T10:02:47.691000Z,2025-12-10T10:32:39.947000Z,2025-12-13T18:21:05.864000Z,2025-12-10T10:32:40.273221Z,1793.0,CXOHLI21,2,21,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Unemployed (and job seeking)
35,693945bfcdf3d1e39f7c47bb,67698e94c727a4a942390c57,APPROVED,Not Applicable,2025-12-10T10:04:51.895000Z,2025-12-10T10:35:48.442000Z,2025-12-13T18:22:04.620000Z,2025-12-10T10:36:09.616130Z,1857.0,CXOHLI21,1487,61,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,DATA_EXPIRED,DATA_EXPIRED
36,69394f2196b78664394073c4,5f4e8bbd350d2a08d6175762,APPROVED,Not Applicable,2025-12-10T10:44:54.204000Z,2025-12-10T10:59:17.093000Z,2025-12-13T18:27:40.735000Z,2025-12-10T10:59:26.539762Z,863.0,CXOHLI21,176,34,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
37,6939503bc782277bfb52e131,69262c7d3bf2812cd35a933d,APPROVED,Not Applicable,2025-12-10T10:49:37.605000Z,2025-12-10T11:05:44.325000Z,2025-12-13T18:49:48.965000Z,2025-12-10T11:05:44.685500Z,967.0,CXOHLI21,12,33,Female,White,Hungary,Netherlands,Hungary,Hungarian,No,Unemployed (and job seeking)
38,693954e07fef04ab2b207b0e,5f3013e31c8a690aacb02c31,APPROVED,Not Applicable,2025-12-10T11:09:28.404000Z,2025-12-10T11:43:41.240000Z,2025-12-13T18:50:04.654000Z,2025-12-10T11:43:41.686657Z,2053.0,CXOHLI21,2514,33,Female,White,Hungary,United Kingdom,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
39,69396d9d0776dd10f09f06ff,604dedd2805fe682c5bc51c0,APPROVED,Not Applicable,2025-12-10T12:54:58.179000Z,2025-12-10T13:15:03.999000Z,2025-12-13T18:50:18.793000Z,2025-12-10T13:15:04.318507Z,1206.0,CXOHLI21,829,41,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
40,69398e7c88dbe3546e02861e,6932be225beb1292d32a80c0,APPROVED,Not Applicable,2025-12-10T15:15:14.273000Z,2025-12-10T15:35:36.457000Z,2025-12-13T17:11:47.621000Z,2025-12-10T15:35:36.803282Z,1223.0,CXOHLI21,1,20,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Part-Time
41,6939b5cd140ecb6c99922480,63d7b1d1d1cba5b706f4004d,APPROVED,Not Applicable,2025-12-10T18:02:53.646000Z,2025-12-10T18:25:26.815000Z,2025-12-13T18:17:20.797000Z,2025-12-10T18:25:27.162358Z,1354.0,CXOHLI21,5,37,Female,White,Hungary,United Kingdom,United Kingdom,Hungarian,No,Part-Time
42,6939bdb102f86650672d9272,60eeb5c2667ce4a8a80521c9,APPROVED,Not Applicable,2025-12-10T18:36:40.865000Z,2025-12-10T18:58:41.101000Z,2025-12-15T01:50:52.822000Z,2025-12-10T18:58:41.449986Z,1321.0,NOCODE,38,23,Male,White,Hungary,Hungary,Hungary,Hungarian,Yes,Part-Time
43,6939eff6910dc57b2b4a7980,60cb4cd6477b2ff7c1adaea4,APPROVED,Not Applicable,2025-12-10T22:11:11.117000Z,2025-12-10T22:26:21.878000Z,2025-12-13T20:12:25.079000Z,2025-12-10T22:26:22.221917Z,911.0,CXOHLI21,557,37,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
44,693a7cd9737f56a416655d43,610bfb5a1da99c3da6313a50,APPROVED,Not Applicable,2025-12-11T08:12:13.884000Z,2025-12-11T08:30:46.508000Z,2025-12-13T20:14:34.728000Z,2025-12-11T08:30:46.844196Z,1113.0,CXOHLI21,191,44,Female,White,Hungary,Hungary,Hungary,Hungarian,No,Full-Time
45,693ab70296bf45483d4c6599,5cb9d45ac3eb6a00123c226e,APPROVED,Not Applicable,2025-12-11T12:20:22.373000Z,2025-12-11T12:45:12.462000Z,2025-12-13T20:14:48.646000Z,2025-12-11T12:45:12.800556Z,1491.0,CXOHLI21,491,32,Male,White,Latvia,United Kingdom,Latvia,Hungarian,No,Full-Time
46,693ab58dc900277730a2e9aa,6932c07f41479348b6b5d9fb,APPROVED,Not Applicable,2025-12-11T12:16:38.367000Z,2025-12-11T13:10:20.425000Z,2025-12-13T18:12:08.184000Z,2025-12-11T13:10:20.975831Z,3223.0,CXOHLI21,1,25,Female,Mixed,Hungary,Hungary,Hungary,Hungarian,Yes,Unemployed (and job seeking)
47,693b0303ec4254db0f80cbcc,5e3b29dc87243b34bde5abfa,APPROVED,Not Applicable,2025-12-11T17:47:14.784000Z,2025-12-11T18:00:46.492000Z,2025-12-13T20:15:00.629000Z,2025-12-11T18:00:46.853630Z,812.0,CXOHLI21,620,47,Male,White,Hungary,Hungary,Hungary,Hungarian,No,Unemployed (and job seeking)
48,693b115bdc02110dbce568cb,6153ff2b2d71a6a4c3789a93,APPROVED,Not Applicable,2025-12-11T18:45:50.145000Z,2025-12-11T18:59:52.876000Z,2025-12-13T20:15:12.858000Z,2025-12-11T18:59:53.256886Z,843.0,CXOHLI21,317,48,Male,White,Hungary,Hungary,Hungary,Hungarian,DATA_EXPIRED,DATA_EXPIRED
49,693d14957377b084c6d3554e,693d10ff23f42886b9051c5f,APPROVED,Not Applicable,2025-12-13T07:24:15.764000Z,2025-12-13T07:56:32.984000Z,2025-12-13T18:17:31.505000Z,2025-12-13T07:56:33.518200Z,1938.0,NOCODE,0,21,Female,White,Serbia,Hungary,DATA_EXPIRED,Hungarian,Yes,Part-Time
50,693fb5c8334778a3e2855a1e,693c768c138df103c91b6c22,APPROVED,Not Applicable,2025-12-15T07:16:35.685000Z,2025-12-15T07:38:13.471000Z,2026-01-05T00:00:35.742000Z,2025-12-15T07:38:13.812262Z,1298.0,CXOHLI21,0,33,Male,White,Hungary,Hungary,DATA_EXPIRED,Hungarian,No,Full-Time
51,693fe07fd7b8f13d5b033519,6932b2822d8f41f447a6bb6b,APPROVED,Not Applicable,2025-12-15T10:18:49.956000Z,2025-12-15T10:35:44.386000Z,2026-01-05T00:00:36.078000Z,2025-12-15T10:35:44.970150Z,1015.0,CXOHLI21,1,34,Male,White,Hungary,Hungary,DATA_EXPIRED,Hungarian,No,Full-Time

In [7]:
age_summary = accepted["Age"].describe().to_frame().T
gender_summary = (
    accepted["Sex"]
    .str.title()
    .value_counts(dropna=False)
    .rename_axis("Sex")
    .to_frame("count")
 )
gender_summary["percent"] = (gender_summary["count"] / gender_summary["count"].sum() * 100).round(1)

total_participants = len(accepted)
age_summary, gender_summary, total_participants

(     count       mean        std   min    25%   50%    75%   max
 Age   52.0  35.038462  10.247834  20.0  25.75  33.5  40.25  61.0,
                    count  percent
 Sex
 Female                32     61.5
 Male                  19     36.5
 Prefer Not To Say      1      1.9,
 52)

In [8]:
mean_age = age_summary.loc["Age", "mean"]
std_age = age_summary.loc["Age", "std"]
min_age = age_summary.loc["Age", "min"]
max_age = age_summary.loc["Age", "max"]

gender_parts = ", ".join(
    f"{sex.lower()} {row['percent']:.1f}% (n={row['count']})"
    for sex, row in gender_summary.iterrows()
)

summary_note = (
    f"The analytic sample comprised {total_participants} approved Prolific participants "
    f"(M_age = {mean_age:.1f} years, SD = {std_age:.1f}, range = {min_age:.0f}–{max_age:.0f}). "
    f"Gender composition was {gender_parts}."
)
print(summary_note)

The analytic sample comprised 52 approved Prolific participants (M_age = 35.0 years, SD = 10.2, range = 20–61). Gender composition was female 61.5% (n=32.0), male 36.5% (n=19.0), prefer not to say 1.9% (n=1.0).

## Plotly donut charts
Interactive visuals to quickly scan gender distribution and age-band composition among accepted participants.

In [9]:
gender_fig = px.pie(
    gender_summary.reset_index(),
    names="Sex",
    values="count",
    hole=0.4,
    title=f"Gender distribution (accepted participants, n={total_participants})",
    color_discrete_sequence=px.colors.qualitative.Pastel,
)
# balance label visibility for print/export
gender_fig.update_traces(
    texttemplate="<b>%{label}</b><br>n=%{value}<br>%{percent}",
    textfont=dict(size=24, family="Times New Roman"),
    hovertemplate="%{label}: %{value} participants",
)
# square canvas so the two donuts sit side-by-side cleanly
gender_fig.update_layout(
    width=700,
    height=700,
    margin=dict(l=20, r=20, t=60, b=20),
    font=dict(size=24, family="Times New Roman"),
    showlegend=False,
)

# Save fig to plots (square export)
gender_fig.write_image("plots/demographics_gender_pie.png", width=1400, height=1400, scale=3)

# show fig
gender_fig

In [10]:
age_bins = pd.cut(
    accepted["Age"],
    bins=[18, 25, 30, 35, 40, 50, 60, 69],
    labels=["18-24", "25-29", "30-34", "35-39", "40-49", "50-59", "60+"],
    right=False,
)

# enforce logical ascending order for plotting
age_order = ["18-24", "25-29", "30-34", "35-39", "40-49", "50-59", "60+"]
age_counts = (
    age_bins.value_counts(sort=False)
    .reindex(age_order, fill_value=0)
    .reset_index()
)
age_counts.columns = ["Age band", "count"]

age_fig = px.pie(
    age_counts,
    names="Age band",
    values="count",
    hole=0.5,
    title=f"Age bands (accepted participants, n={total_participants})",
    color_discrete_sequence=px.colors.qualitative.Set3,
    category_orders={"Age band": age_order},
)
age_fig.update_traces(
    texttemplate="<b>%{label}</b><br>n=%{value}<br>%{percent}",
    textfont=dict(size=24, family="Times New Roman"),
    hovertemplate="%{label}: %{value} participants",
)

# square canvas to align with gender chart
age_fig.update_layout(
    width=700,
    height=700,
    margin=dict(l=20, r=20, t=60, b=20),
    font=dict(size=24, family="Times New Roman"),
)

# Save fig to plots (square export)
age_fig.write_image("plots/demographics_age_pie.png", width=1400, height=1400, scale=3)

# show fig
age_fig

In [13]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

gender_colors = px.colors.qualitative.Pastel
age_colors = px.colors.qualitative.Set3

combined_fig = make_subplots(
    rows=1,
    cols=2,
    specs=[[{"type": "domain"}, {"type": "domain"}]],
    subplot_titles=[
        f"Gender (n={total_participants})",
        f"Age bands (n={total_participants})",
    ],
)

combined_fig.add_trace(
    go.Pie(
        labels=gender_summary.index,
        values=gender_summary["count"],
        hole=0.4,
        marker=dict(colors=gender_colors),
        texttemplate="<b>%{label}</b><br>n=%{value}<br>%{percent}",
        textfont=dict(size=24, family="Times New Roman"),
        hovertemplate="%{label}: %{value} participants",
    ),
    row=1,
    col=1,
)

combined_fig.add_trace(
    go.Pie(
        labels=age_counts["Age band"],
        values=age_counts["count"],
        hole=0.4,
        marker=dict(colors=age_colors),
        texttemplate="<b>%{label}</b><br>n=%{value}<br>%{percent}",
        textfont=dict(size=24, family="Times New Roman"),
        hovertemplate="%{label}: %{value} participants",
    ),
    row=1,
    col=2,
)

combined_fig.update_layout(
    width=1200,
    height=500,
    margin=dict(l=0, r=0, t=40, b=0),
    font=dict(size=24, family="Times New Roman"),
    showlegend=False,
)

for ann in combined_fig.layout.annotations:
    ann.font.size = 24
    ann.font.family = "Times New Roman"

combined_fig.show()

combined_fig.write_image("plots/demographics_combined_donuts.png", scale=2)

In [12]:
# Approximate mean age using band midpoints
age_band_midpoints = {
    "18-24": 21,
    "25-29": 27,
    "30-34": 32,
    "35-39": 37,
    "40-49": 44.5,
    "50-59": 54.5,
    # upper bin spans 60–69 (changed upper cut to 69); use its midpoint
    "60+": 64.5,
}

age_band_mean = (
    age_counts.assign(midpoint=lambda df: df["Age band"].map(age_band_midpoints))
    .pipe(lambda df: (df["count"] * df["midpoint"]).sum() / df["count"].sum())
)

print(f"Mean age (band midpoint weighted): {age_band_mean:.1f} years")

Mean age (band midpoint weighted): 35.1 years